{{- if .Values.services }}
{{- range .Values.services }}
{{- if and .failover .failover.enabled .failover.trafficPolicySpec }}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: {{ .serviceId }}-failover-policy
  namespace: {{ $.Values.global.namespace | default "path" }}
  labels:
    {{- include "guard.labels" $ | nindent 4 }}
    service-id: {{ .serviceId }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: {{ $.Values.fullnameOverride | default "guard" }}-subdomain-{{ .serviceId }}
  {{- toYaml .failover.trafficPolicySpec | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}