# MCG performs health checks against services to which it routes traffic.
# To remove the need for customizing MCG health checks, this HTTPRoute resource directs traffic from `/'` (MCG's default healthcheck path) to `/healthz`
#
# HTTPRoute Generator to direct requests with no prefix to the healthcheck endpoint.
#
# Generates an HTTPRoute resource for the healthz endpoint.
#
# Ref: https://gateway.envoyproxy.io/latest/api/gateway_api/httproute/
{{- $gwname:= default "guard" $.Values.fullnameOverride }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: healthz-route-no-prefix
  namespace: {{ $.Values.global.namespace }}
spec:
  parentRefs:
  {{- range $.Values.gatewayRef }}
  - group: {{ .group }}
    kind: {{ .kind }}
    name: {{ .name }}
  {{- end }}
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: {{ $.Values.healthCheck.serviceName | default $.Values.global.serviceName }}
          namespace: {{ $.Values.healthCheck.namespace | default $.Values.global.namespace }}
          port: {{ $.Values.healthCheck.port | default $.Values.global.port }}
      matches:
        - path:
            type: Exact
            value: /
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: {{ $.Values.healthCheck.path | default "/healthz" }}
