{{- if and .Values.auth.debug_endpoints .Values.auth.debug_endpoints.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: debug-endpoints-route
  namespace: {{ .Values.global.namespace }}
  annotations:
    gateway.envoyproxy.io/route-priority: "100"
spec:
  parentRefs:
  {{- range .Values.gatewayRef }}
  - group: {{ .group }}
    kind: {{ .kind }}
    name: {{ .name }}
  {{- end }}
  rules:
  {{- if .Values.auth.debug_endpoints.pprofServiceName }}
  # pprof endpoints
  - matches:
    - path:
        type: PathPrefix
        value: /debug/pprof/
    backendRefs:
    - group: ""
      kind: Service
      name: {{ .Values.auth.debug_endpoints.pprofServiceName }}
      namespace: {{ .Values.global.namespace }}
      port: {{ .Values.auth.debug_endpoints.pprofPort | default 6060 }}
      weight: 1
  {{- end }}
  # disqualified_endpoints served on port 3069 via main API service
  - matches:
    - path:
        type: Exact
        value: /disqualified_endpoints
    backendRefs:
    - group: ""
      kind: Service
      name: {{ .Values.global.serviceName }}
      namespace: {{ .Values.global.namespace }}
      port: {{ .Values.global.port }}
      weight: 1
{{- end }}