# HTTPRoute Generator for Healthz
#
# Generates an HTTPRoute resource for the healthz endpoint.
#
# Ref: https://gateway.envoyproxy.io/latest/api/gateway_api/httproute/
{{- $gwname:= default "guard" $.Values.fullnameOverride }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: healthz-route
  namespace: {{ $.Values.global.namespace }}
spec:
  parentRefs:
  {{- range $.Values.gatewayRef }}
  - group: {{ .group }}
    kind: {{ .kind }}
    name: {{ .name }}
  {{- end }}
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: {{ $.Values.healthCheck.serviceName | default $.Values.global.serviceName }}
          namespace: {{ $.Values.healthCheck.namespace | default $.Values.global.namespace }}
          port: {{ $.Values.healthCheck.port | default $.Values.global.port }}
          weight: 1
      matches:
        # /healthz route returns the health of the PATH service.
        - path:
            type: Exact
            value: {{ $.Values.healthCheck.path | default "/healthz" }}
