# TODO_TECHDEBT(@adshmh): Review whether debug endpoints should go through Envoy:
# - PATH instances have separate state, making correlation impossible
# - Not available in prod, local development only
# - Workaround: kubectl port-forward to specific pods
# - Long-term: Tailscale access
# - Need: Document port-forward instructions
#
{{- if .Values.auth.debug_endpoints }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: debug-endpoints-route
  namespace: {{ .Values.global.namespace }}
  annotations:
    gateway.envoyproxy.io/route-priority: "100"
spec:
  parentRefs:
  {{- range .Values.gatewayRef }}
  - group: {{ .group }}
    kind: {{ .kind }}
    name: {{ .name }}
  {{- end }}
  rules:
  # pprof endpoints - correct service name is "path-pprof"
  - matches:
    - path:
        type: PathPrefix
        value: /debug/pprof/
    backendRefs:
    - name: path-pprof
      namespace: {{ .Values.global.namespace }}
      port: 6060
  # disqualified_endpoints served on port 3069 via main API service
  - matches:
    - path:
        type: Exact
        value: /disqualified_endpoints
    backendRefs:
    - name: {{ .Values.global.serviceName }}
      namespace: {{ .Values.global.namespace }}
      port: {{ .Values.global.port }}
{{- end }}
