# HTTPRouteFilter for External Backend URL Rewriting
#
# Creates HTTPRouteFilter resources that strip the /v1/<appid> prefix
# for external backends. These are referenced by HTTPRoutes.
#
{{- range .Values.services }}
{{- $service := . }}
{{- $ts := default dict .trafficSplitting }}
{{- if and (eq $ts.enabled true) $ts.external }}
{{- range $index, $external := $ts.external }}
{{- if gt (default 0 ($external.weight | int)) 0 }}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: HTTPRouteFilter
metadata:
  name: {{ $service.serviceId }}-external-{{ $index }}-rewrite
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{- include "guard-helm.labels" $ | nindent 4 }}
    service-id: {{ $service.serviceId }}
spec:
  urlRewrite:
    path:
      type: ReplaceRegexMatch
      replaceRegexMatch:
        pattern: "^/v1/[^/]+"
        substitution: ""
{{- end }}
{{- end }}
{{- end }}
{{- end }}