# HTTPRoute Generator for Healthz
#
# Generates an HTTPRoute resource for the healthz endpoint.
#
# Ref: https://gateway.envoyproxy.io/latest/api/gateway_api/httproute/
{{- $gwname:= default "guard" $.Values.fullnameOverride }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: healthz-route
  namespace: {{ $.Values.global.namespace }}
spec:
  parentRefs:
  - kind: Gateway
    name: {{$gwname}}-envoy-gateway
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: {{ $.Values.global.serviceName }}
          port: {{ $.Values.global.port }}
          weight: 1
      matches:
        # /healthz route returns the health of the PATH service.
        - path:
            type: Exact
            value: /healthz
