# TODO_MVP(@adshmh): Use v1beta1 as version. `v1lapha2` is used to stay compatible with the existing infra tooling.
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: ReferenceGrant
metadata:
  name: allow-middleware-reference
  # To the Middleware Service's namespace
  namespace: {{ $.Values.global.middlewareNamespace }}
spec: 
  # From the PATH namespace
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: {{ $.Values.global.namespace }}
  # To the Middleware Service
  to:
  - group: ""
    kind: Service
    name: {{ $.Values.global.middlewareServiceName }}
