{{- if and .Values.serviceMonitors.guard.enabled (index .Values "kube-prometheus-stack" "enabled") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "watch.fullname" . }}-guard
  namespace: {{ include "watch.namespace" (list "servicemonitor" .) }}
  labels:
    {{- include "watch.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: watch-monitoring
    release: {{ .Release.Name }}
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      {{- toYaml .Values.serviceMonitors.guard.selector.matchLabels | nindent 6 }}
  endpoints:
    {{- toYaml .Values.serviceMonitors.guard.endpoints | nindent 4 }}
{{- end }}
