apiVersion: v2
name: guard
description: A Helm chart for development and production deployments of GUARD (Gateway Utilities for Authentication, Routing & Defense)
version: 0.1.1
appVersion: "1.0"
dependencies:
  - name: gateway-helm
    version: v1.3.0
    repository: "oci://docker.io/envoyproxy"
