apiVersion: v2
name: guard
description: A Helm chart for deploying GUARD (Gateway Utilities for Authentication, Routing & Defense) in production or development environments
version: 0.1.1
appVersion: "1.0"
dependencies:
  - name: gateway-helm
    version: v1.3.0
    repository: "oci://docker.io/envoyproxy"
