apiVersion: v2
appVersion: "1.0"
description: A Helm chart for development and production deployments of GUARD (Gateway Utilities for Authentication, Routing & Defense)
name: guard
type: application
version: 0.1.11
dependencies:
  - name: gateway-helm
    version: v1.3.0
    repository: https://buildwithgrove.github.io/helm-charts/
