apiVersion: v2
appVersion: "1.0"
description: A Helm chart for development and production deployments of GUARD (Gateway Utilities for Authentication, Routing & Defense)
name: guard
type: application
version: 0.1.27
dependencies:
  - name: gateway-helm
    repository: oci://docker.io/envoyproxy
    version: v1.4.0
    condition: envoyGateway.enabled
