# This file provides only the field names and descriptions, with all default values
# set by the `guard` field in the PATH Helm Chart's `values.yaml` file.
#
# See: https://github.com/buildwithgrove/helm-charts/blob/main/charts/path/values.yaml
fullnameOverride: guard
global:
  serviceName: path-http
  port: 3069
  # -- CONTROLLED TRAFFIC SHIFTING --
  # This variable must correspond to the name of the Middleware Service
  # that is deployed in the same namespace as PATH/GUARD.
  # Defined in `charts/path/values.yaml`
  middlewareServiceName: middleware-http
  # -- CONTROLLED TRAFFIC SHIFTING --
  # This variable must correspond to the port of the Middleware Service
  # in the same namespace as PATH/GUARD.
  # Defined in `charts/path/values.yaml`
  middlewarePort: 3000
gateway:
  port: 3070
domain: ""
services: []
auth:
  apiKey:
    enabled: false
    headerKey: ""
    apiKeys: []
  groveLegacy:
    enabled: true
    peas:
      enabled: false
    pads:
      enabled: true
      envFrom:
        - secretRef: 
            name: pads-db-connection
      mountPath: /app/data
      fromSecret:
        secretName: pads-config
