# This file provides only the field names and descriptions, with all default values
# set by the `guard` field in the PATH Helm Chart's `values.yaml` file.
#
# See: https://github.com/buildwithgrove/helm-charts/blob/main/charts/path/values.yaml
fullnameOverride: guard
global:
  namespace: path
  serviceName: path-http
  port: 3069
  # -- CONTROLLED TRAFFIC SHIFTING --
  # This variable must correspond to the Middleware Service's namespace.
  middlewareNamespace: middleware
  # -- CONTROLLED TRAFFIC SHIFTING --
  # This variable must correspond to the name of the Middleware Service
  # that is deployed in the same namespace as PATH/GUARD.
  # Defined in `charts/path/values.yaml`
  middlewareServiceName: middleware-http
  # -- CONTROLLED TRAFFIC SHIFTING --
  # This variable must correspond to the port of the Middleware Service
  # in the same namespace as PATH/GUARD.
  # Defined in `charts/path/values.yaml`
  middlewarePort: 8080
gateway:
  port: 3070
# ** IMPORTANT: update domain value: **
# ** - domain must be specified in HTTPRoute resources for proper request routing. **
# ** - domain must match the Host header value in HTTP requests received by GUARD/Envoy Gateway. **
domain: "example.com"
# **IMPORTANT: specify at least one service: otherwise no requests will be accepted by Envoy Gateway.
services:
  # Morse-specific services
  - serviceId: F00C
    aliases:
      - eth
      - eth-mainnet
    # TODO_MVP(@adshmh): Required by Grove for migration to PATH. Remove once the migration is completed.
    #trafficSplitting:
    #  enabled: true
    #  weights:
    #    path: 70
    #    middleware: 30
auth:
  apiKey:
    enabled: true
    headerKey: ""
    apiKeys: []
  groveLegacy:
    enabled: false
    peas:
      enabled: false
    pads:
      enabled: true
      envFrom:
        - secretRef:
            name: pads-db-connection
      mountPath: /app/data
      fromSecret:
        secretName: pads-config

envoyGateway:
  enabled: true
  serviceType: ClusterIP

middlewareNamespaceReferenceGrant:
  enabled: false
