# This file provides only the field names and descriptions, with all default values
# set by the `guard` field in the PATH Helm Chart's `values.yaml` file.
#
# See: https://github.com/buildwithgrove/helm-charts/blob/main/charts/path/values.yaml
fullnameOverride: guard
global:
  serviceName: path-http
  port: 3069
gateway:
  port: 3070
domain: ""
services: []
auth:
  apiKey:
    enabled: true
    headerKey: ""
    apiKeys: []
  groveLegacy:
    enabled: false
    peas:
      enabled: false
    pads:
      enabled: false
