# ---- Envoy Gateway ----
gateway:
  enabled: true
  gatewayClassName: envoy-gateway-class
  listeners:
    # Envoy Gateway will listen for HTTP requests on port 3070.
    - name: http
      protocol: HTTP
      port: 3070

# ---- Global settings ----
# These settings may be overridden in a guard-values.yaml file for production use.

# Domain is the base domain for subdomain matching.
# For Example:  
# - ethereum: eth.path.grove.city -> "target-service-id: F00C"
# - polygon: polygon.path.grove.city -> "target-service-id: F021"
domain: path.grove.city 
# namespace is the namespace that both Envoy Gateway and the PATH service are deployed to.
namespace: path-local 
# serviceName is the name of the service that the PATH service is deployed to.
serviceName: path-http 
# Port is the port that the PATH service runs on in the cluster.
# This is the port that Envoy Gateway will forward requests to.
port: 3069

# ---- Service routing settings ----

# List of services that will be routed by Envoy Gateway
# to the PATH backend. These services will be used to 
# construct HTTPRoutes for each service. These HTTPRoutes
# are used to assign the "target-service-id" header to the 
# request based on the subdomain service alias.
# - serviceId [REQUIRED]: The authorative service ID of the service.
# - aliases [OPTIONAL]: A list of aliases for the service.
#
# For example:
# - F00C.path.grove.city -> "target-service-id: F00C"
# - eth.path.grove.city -> "target-service-id: F00C"
# - polygon.path.grove.city -> "target-service-id: F021"
services:
  - serviceId: F00C
    aliases: 
      - eth
      - eth-mainnet
  - serviceId: F021
    aliases: 
      - polygon
      - polygon-mainnet

# Add other services here ...

# ---- Gateway Endpoints ----

# Gateway endpoints define the allowed endpoints for a PATH instance.
# For a detailed breakdown of the possible format of this file, see:
# - https://path.grove.city/develop/envoy/envoy_config#4-gateway-endpoints-data---gateway-endpointsyaml
# - https://path.grove.city/develop/envoy/walkthrough#gateway-endpoint-authorization
#
# IMPORTANT: This default value should be overridden in a `guard-values.yaml` file for production use.
# This value is only used if a database is not used as the data source.
gatewayEndpointsData: |
  endpoints:                
    test_endpoint:                                               
      auth:
        api_key: "test_api_key"
