# TODO_TECHDEBT(@adshmh,@commoddity,@HebertCL): The pre-commit is disabled for now,
# in favour of manually regenerating the docs. In the future, we should determine 
# an approach that works for us and re-enable the pre-commit.
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
- repo: https://github.com/buildwithgrove/helm-charts
  rev: docs-hook-0.1.2
  hooks:
    - id: helm-docs
      args: []
