apiVersion: v2
appVersion: 0.0.16
description: A Helm chart for PATH (PATH API & Toolkit Harness)
name: path
type: application
version: 0.1.17
dependencies:
  - name: guard
    version: "0.1.16"
    repository: "https://buildwithgrove.github.io/helm-charts"
  - name: watch
    version: "0.1.11"
    repository: "https://buildwithgrove.github.io/helm-charts"
