apiVersion: v2
appVersion: 0.0.16
description: A Helm chart for PATH (PATH API & Toolkit Harness)
name: path
type: application
version: 0.1.25
dependencies:
  # TODO: Remove dependencies for internal charts.
  - name: guard
    version: "0.1.24"
    repository: "https://buildwithgrove.github.io/helm-charts"
    condition: guard.enabled
  - name: watch
    version: "0.1.11"
    repository: "https://buildwithgrove.github.io/helm-charts"
    condition: observability.enabled
