apiVersion: v2
appVersion: 0.0.24
description: PATH (Path API & Toolkit Harness) is an open source framework for enabling access to a decentralized supply network. It provides various tools and libraries to streamline the integration and interaction with decentralized protocols.
name: path
type: application
version: 0.1.22
