apiVersion: v2
appVersion: 0.0.16
description: A Helm chart for Kubernetes
name: path
type: application
version: 0.1.9
dependencies:
  - name: guard
    version: 0.1.1
    repository: https://buildwithgrove.github.io/helm-charts/
