{{ $name := include "path.name" . }}
{{- range $kprt, $prt := $.Values.path.ports }}

apiVersion: v1
kind: Service
metadata:
  name: {{$name}}-{{ $prt.name }}
  labels:
    app: {{$name}}
spec:
  selector:
    app: {{$name}}
  ports:
    - name: {{ $prt.name }}
      protocol: {{ $prt.protocol }}
      port: {{ $prt.port }}
      targetPort: {{ $prt.port }}

{{- end -}}
