# PATH Auth Data Server (PADS) Helm Chart
# Used as part of the Grove legacy authorization flow.
#
# A gRPC server that provides Gateway Endpoint data from a configurable data source
# to the Go External Authorization Server, enabling authorization for the PATH Gateway.
#
# Data sources can include:
#   - YAML files
#   - Postgres databases
#
# Github Repo: https://github.com/buildwithgrove/path-auth-data-server
{{- if .Values.auth.groveLegacy.enabled }}
{{- $name := include "guard-helm.fullname" . }}
{{- $padsConfig:= .Values.auth.groveLegacy.pads }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{$name}}-pads
  labels:
    {{- include "guard-helm.labels" $ | nindent 4 }}
spec:
  replicas: {{ $padsConfig.replicas }}
  selector:
    matchLabels:
      app: {{$name}}-pads
  template:
    metadata:
      labels:
        {{- include "guard-helm.labels" $ | nindent 8 }}
        app: {{$name}}-pads
    spec:
      containers:
      - name: path-auth-data-server
        image: ghcr.io/buildwithgrove/path-auth-data-server:latest
        imagePullPolicy: IfNotPresent
        env: {{- toYaml $padsConfig.env | nindent 10 }}
        ports:
        - containerPort: {{ $padsConfig.port }}
        volumeMounts:
          - name: {{$name}}-data
            mountPath: {{ .Values.pads.mountPath }}
      volumes:
      - name: {{$name}}-data
        configMap:
          name: pads-data
---
apiVersion: v1
kind: Service
metadata:
  name: {{$name}}-pads
  labels:
    {{- include "guard-helm.labels" $ | nindent 4 }}
spec:
  selector:
    app: {{$name}}-pads
  ports:
  - port: {{ $padsConfig.port }}
    targetPort: {{ $padsConfig.port }}
    protocol: TCP
    name: grpc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pads-data
data: {{- toYaml $padsConfig.configMap | nindent 4 }}

{{- end }}
