# --------- VERY IMPORTANT ---------
# Only use if you are authorizing Grove Portal requests.
#   - Not likely to fit other use-cases.
#
# PATH External Authorization Server (PEAS) Helm Chart
#   - Used for Grove legacy authorization flow.
#   - Github: https://github.com/buildwithgrove/path-external-auth-server
#
# PEAS is a custom external authorization server for the PATH Gateway:
#   - Built for unique Grove Portal App needs
#   - Not handled by default Envoy Gateway features
#   - Uses gRPC for communication
#   - Follows Envoy External Authorization HTTP Filter spec
#
# References:
#   - Envoy Gateway Ext Auth: https://gateway.envoyproxy.io/docs/tasks/security/ext-auth/
#   - Envoy Proxy Ext Authz Filter: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/ext_authz_filter
{{- if .Values.auth.groveLegacy.enabled }}
{{- $name:= include "guard-helm.fullname" . }}
{{- $peasConfig:= .Values.auth.groveLegacy.peas }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{$name}}-peas
  namespace: {{ $.Values.global.namespace }}
spec:
  replicas: {{ $peasConfig.replicas }}
  selector:
    matchLabels:
      app: {{$name}}-peas
  template:
    metadata:
      labels:
        {{- include "guard-helm.labels" $ | nindent 8 }}
        app: {{$name}}-peas
    spec:
      containers:
      - name: path-external-auth-server
        image: ghcr.io/buildwithgrove/path-external-auth-server:{{ default "latest" $peasConfig.imageTag }}
        imagePullPolicy: IfNotPresent
        {{- with $peasConfig.envFrom }}
        envFrom: {{- toYaml . | nindent 10}}
        {{- end }}
        env: {{- toYaml $peasConfig.env | nindent 10 }}
        ports:
        - containerPort: {{ $peasConfig.port }}
        volumeMounts:
          - name: {{$name}}-data
            mountPath: {{ $peasConfig.mountPath }}
          {{- range $peasConfig.secretMounts }}
          - name: {{ .name }}
            mountPath: {{ .mountPath }}
            {{- if .subPath }}
            subPath: {{ .subPath }}
            {{- end }}
            {{- if .readOnly }}
            readOnly: {{ .readOnly }}
            {{- end }}
          {{- end }}
      volumes:
      {{- if $peasConfig.fromSecret }}
      - name: {{$name}}-data
        secret:
          secretName: {{ $peasConfig.fromSecret.secretName }}
      {{- else }}
      - name: {{$name}}-data
        configMap:
          name: peas-data
      {{- end }}
      {{- range $peasConfig.secretMounts }}
      - name: {{ .name }}
        secret:
          secretName: {{ .secretName }}
          {{- if .defaultMode }}
          defaultMode: {{ .defaultMode }}
          {{- end }}
          {{- if .items }}
          items:
          {{- range .items }}
          - key: {{ .key }}
            path: {{ .path }}
            {{- if .mode }}
            mode: {{ .mode }}
            {{- end }}
          {{- end }}
          {{- end }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{$name}}-peas
  namespace: {{ $.Values.global.namespace }}
spec:
  selector:
    app: {{$name}}-peas
  ports:
  - port: {{ $peasConfig.port }}
    targetPort: {{ $peasConfig.port }}
    protocol: TCP
    name: grpc
---
{{- if not $peasConfig.fromSecret }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: peas-data
  namespace: {{ $.Values.global.namespace }}
data: {{- toYaml $peasConfig.configMap | nindent 4 }}
{{- end }}

{{- end }}
