{{- if and .Values.services .Values.auth.groveLegacy.enabled }}
{{- $name:= include "guard-helm.fullname" . }}

{{- range .Values.services }}
{{- $service := . }}

# Security Policies for PATH External Authorization Server (PEAS)
# Used as part of the Grove legacy authorization flow.
# If you are not authorizing Grove Portal requests,
# this is VERY unlikely to fit your exact use-case.
#
# Creates a security policy for each service in the `services` list.
#
# The security policies ensure that requests to the service are authorized
# through the PATH External Authorization Server (PEAS).

# Create a security policy for the subdomain route.
# eg. F00C-subdomain-auth-policy
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: {{ $service.serviceId | lower }}-subdomain-auth-policy
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      # eg. F00C-subdomain-route - matches the HTTPRoute resource created above
      name: {{ $service.serviceId | lower }}-subdomain-route
  extAuth:
    grpc:
      backendRefs:
        - name: {{$name}}-peas
          port: 10001

# Create a security policy for the header route.
# eg. F00C-header-auth-policy
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: {{ $service.serviceId | lower }}-header-auth-policy
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      # eg. F00C-header-route - matches the HTTPRoute resource created above
      name: {{ $service.serviceId | lower }}-header-route
  extAuth:
    grpc:
      backendRefs:
        - name: {{$name}}-peas
          port: 10001

# If the service has aliases, create a SecurityPolicy resource for each alias.
{{- if $service.aliases }}
{{- range $service.aliases }}
{{- $alias := . }}

# Create a security policy for the alias header route.
# eg. F00C-eth-alias-auth-policy
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: {{ $service.serviceId | lower }}-{{ $alias | lower }}-alias-header-auth-policy
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      # eg. F00C-eth-alias-header-route - matches the HTTPRoute resource created above
      name: {{ $service.serviceId | lower }}-{{ $alias | lower }}-alias-header-route
  extAuth:
    grpc:
      backendRefs:
        - name: {{$name}}-peas
          port: 10001
{{- end }}
{{- end }}

{{- end }}

{{- end }}
