#!/usr/bin/env bash

set -e

if ! command -v helm-docs > /dev/null 2>&1; then
    echo "Please install helm-docs to run the pre-commit hook!"
    exit 1
fi

git diff --dirstat=files,0 HEAD | awk '{print $2}' | while read chart; do cd $chart && helm-docs && cd -; done
