{{- if and .Values.rateLimit.enabled .Values.rateLimit.plans }}
{{- $gwname:= default "guard" $.Values.fullnameOverride }}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy 
metadata:
  name: {{ $gwname }}-rate-limit-policy
  namespace: {{ $.Values.global.namespace }}
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{$gwname}}-envoy-gateway
  rateLimit:
    type: Global
    global:
      # Ensure that the rate limit is shared across all HTTPRoutes
      shared: true
      rules:
{{- range .Values.rateLimit.plans }}
      - clientSelectors:
        - headers:
          - type: Distinct
            name: {{ .header }}
        limit:
          requests: {{ .requests }}
          unit: {{ .unit }}
{{- end }}
{{- end }}
