{{- if and .Values.guard.services .Values.guard.gateway.enabled .Values.guard.auth.apiKey.enabled }}
{{- $apiKeyConfig:= .Values.guard.auth.apiKey }}

# This secret is used to store a full list of API keys for the PATH service.
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: api-keys-secret
stringData:
  {{- toYaml $apiKeyConfig.apiKeys | nindent 2 }}

{{- end }}
