{{- if and .Values.services .Values.gateway.enabled .Values.auth.apiKey.enabled }}
{{- $apiKeyConfig:= .Values.auth.apiKey }}

# This secret is used to store a full list of API keys for the PATH service.
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: api-keys-secret
stringData:
  # Populate the secret with the API keys from the `apiKeys` field in the
  # `auth` section of the `values.yaml` file.
  # The `key` is unused; only the `value` (API key) is used.
  #
  # For example:
  # client_1: test_api_key
  # client_2: another_api_key
  {{- range $index, $value := $apiKeyConfig.apiKeys }}
  client_{{ add $index 1 }}: {{ $value | quote }}
  {{- end }}

{{- end }}
