# This resources configures the Envoy Gateway for GUARD.
# Ref: https://gateway.envoyproxy.io/latest/api/gateway_api/gateway/
{{- $gwname:= default "guard" $.Values.fullnameOverride }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{$gwname}}-envoy-gateway
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{- include "guard-helm.labels" $ | nindent 4 }}
  annotations:
    gateway.envoyproxy.io/envoyproxy-name: {{$gwname}}-custom-proxy-config
spec:
  gatewayClassName: {{$gwname}}-envoy-gateway-class
  listeners:
    - name: http
      protocol: HTTP
      port: {{ $.Values.gateway.port }}
      allowedRoutes:
        kinds:
        - kind: HTTPRoute
# Ref: https://gateway.envoyproxy.io/latest/api/gateway_api/gatewayclass/
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{$gwname}}-envoy-gateway-class
  labels:
    {{- include "guard-helm.labels" $ | nindent 4 }}
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller