# PADS (PATH Auth Data Server) is a gRPC server that provides Gateway Endpoint
# data from a data source to the Go External Authorization Server in order to enable
# authorization for the PATH Gateway. The nature of the data source is configurable,
# for example it could be a YAML file or a Postgres database.
#
# Github Repo: https://github.com/buildwithgrove/path-auth-data-server
{{- if .Values.pads.enabled }}
{{- $name:= include "guard-helm.fullname" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{$name}}-pads
  labels:
    {{- include "guard-helm.labels" $ | nindent 4 }}
spec:
  replicas: {{ .Values.pads.replicas }}
  selector:
    matchLabels:
      app: {{$name}}-pads
  template:
    metadata:
      labels:
        {{- include "guard-helm.labels" $ | nindent 8 }}
        app: {{$name}}-pads
    spec:
      containers:
      - name: path-auth-data-server
        image: ghcr.io/buildwithgrove/path-auth-data-server:latest
        imagePullPolicy: IfNotPresent
        env: {{- toYaml .Values.pads.env | nindent 10 }}
        ports:
        - containerPort: {{ .Values.pads.port }}
        # Only mount the volume if the volumeMounts section is set,
        # meaning PADS is using a YAML file as the data source.
        {{- if .Values.pads.volumeMounts }}
        volumeMounts: {{ toYaml .Values.pads.volumeMounts | nindent 10 }}
        {{- end }}
      volumes:
      # Only mount the configMap if the configMap section is set,
      # meaning PADS is using a YAML file as the data source.
      {{- if .Values.pads.configMap }}
      - name: endpoint-data-volume
        configMap:
          name: endpoint-data
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{$name}}-pads
  labels:
    {{- include "guard-helm.labels" $ | nindent 4 }}
spec:
  selector:
    app: {{$name}}-pads
  ports:
  - port: {{ .Values.pads.port }}
    targetPort: {{ .Values.pads.port }}
    protocol: TCP
    name: grpc
# Only create the ConfigMap if the configMap section is set,
# meaning PADS is using a YAML file as the data source.
{{- if .Values.pads.configMap }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: endpoint-data
data:
  .gateway-endpoints.yaml: |-
    {{- index .Values.pads.configMap ".gateway-endpoints.yaml" | nindent 4 }}
{{- end }}

{{- end }}
