{{- if .Values.guard.gateway.enabled }}
{{- $gwname:= default "guard" $.Values.fullnameOverride }}
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{$gwname}}-gwc
  labels:
    {{- include "guard-helm.labels" $ | nindent 4 }}
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---

apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{$gwname}}-gw
  labels:
    {{- include "guard-helm.labels" $ | nindent 4 }}
spec:
  gatewayClassName: eg
  listeners:
    - name: http
      protocol: HTTP
      port: {{ $.Values.guard.gateway.port }}
      allowedRoutes:
        kinds:
        - kind: HTTPRoute

{{- end }}
