---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend
spec:
  parentRefs:
    - name: eg
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: path-http
          port: 3069
          weight: 1
      matches:
        # /healthz route returns the health of the PATH service.
        - path:
            type: PathPrefix
            value: /healthz
        # /v1 route handles all requests to the PATH service.
        # All non-subdomain based service selection will go through this route.
        # For example, when the service ID is specified as the `target-service-id` header.
        - path:
            type: PathPrefix
            value: /v1
