# This template generates an HTTPRoute resource for each service in the `services` list.
# Each HTTPRoute is configured to route requests based on the subdomain of the request,
# which can be either the service ID or any of its aliases.
#
# The `hostnames` field specifies the subdomains that will be matched against the request.
#
# For example, if a service has the following configuration:
#   serviceId: F00C
#   aliases:
#     - eth
#     - eth-mainnet
# The generated HTTPRoute will match requests to:
#   - F00C.path.grove.city
#   - eth.path.grove.city
#   - eth-mainnet.path.grove.city
# All matched requests will have the header "target-service-id: F00C" added.

# Create an HTTPRoute resource for each authoritative service ID.
# This HTTPRoute will also match requests to any of the service's aliases
# through the use of the `hostnames` field.
{{- range .Values.services }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute

metadata:
  # eg. F00C-subdomain-route
  name: {{ .serviceId | lower }}-subdomain-route
  namespace: {{ $.Values.namespace }}

spec: 
  parentRefs:
  - name: eg
    namespace: {{ $.Values.namespace }}

  # Match requests based on their subdomain.
  hostnames:
  - "{{ .serviceId | lower }}.{{ $.Values.domain }}"
  {{- if .aliases }}
  {{- range .aliases }}
  - "{{ . | lower }}.{{ $.Values.domain }}"
  {{- end }}
  {{- end }}

  rules:
  # Determine the backend service to route to.
  - backendRefs:
    - name: {{ $.Values.serviceName }}
      namespace: {{ $.Values.namespace }}
      port: {{ $.Values.port }}

    filters:
    # Ensure the request header "target-service-id" is set to the authoritative service ID.
    - type: RequestHeaderModifier
      requestHeaderModifier:
        set:
        - name: "target-service-id"
          value: "{{ .serviceId }}"

    matches:
    # Match any path prefix that starts with "/v1"
    - path:
        type: PathPrefix
        value: /v1

# TODO_MVP(@commoddity): Modify this config to use TLS for 
# the connection to the external authorization server.
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: {{ .serviceId | lower }}-subdomain-auth-policy
  namespace: {{ $.Values.namespace }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      # eg. F00C-subdomain-route - matches the HTTPRoute resource created above
      name: {{ .serviceId | lower }}-subdomain-route
  extAuth:
    grpc:
      backendRefs:
        - name: ext-auth-server
          port: 10001

{{- end }}
