# This HTTPRoute is a catch all route that returns a 404 Not Found error with a JSON body.
# It is used to catch all requests that do not match any other routes.
#
# For example, if a user makes a request to a service that is not configured in the
# `values.yaml` files' `services` array or a `*-values.yaml` file that is applied to the
# GUARD service, this route will return a 404 Not Found error.
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: resource-not-found
spec:
  parentRefs:
  - name: eg
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: "/"
    filters:
    - type: ExtensionRef
      extensionRef:
        group: gateway.envoyproxy.io
        kind: HTTPRouteFilter
        name: resource-not-found-filter
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: HTTPRouteFilter
metadata:
  name: resource-not-found-filter
spec:
  directResponse:
    contentType: application/json
    statusCode: 404
    body:
      type: Inline
      inline: '{"error": "Resource not found"}'