# This template generates HTTPRoute resources for each service in the `services` list.
# Each HTTPRoute is configured to route requests based on the subdomain of the request.
#
# The `hostnames` field specifies the subdomain that will be matched against the request,
# and the `filters` section assigns the `target-service-id` header to the request based 
# on the subdomain service alias.
#
# For example:
# - ethereum: eth.path.grove.city -> "target-service-id: F00C"
# - polygon: polygon.path.grove.city -> "target-service-id: F021"
#
# The HTTPRoute resources are created based on the `services` list in the `values.yaml` file.
{{- range .Values.services }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .name }}-subdomain-route
  namespace: {{ $.Values.namespace }}
spec:
  parentRefs:
  - name: eg
    namespace: {{ $.Values.namespace }}
  hostnames:
  - "{{ .alias }}.{{ $.Values.domain }}"
  rules:
  - backendRefs:
    - name: {{ $.Values.serviceName }}
      namespace: {{ $.Values.namespace }}
      port: {{ $.Values.port }}
    filters:
    - type: RequestHeaderModifier
      requestHeaderModifier:
        set:
        - name: "target-service-id"
          value: "{{ .id }}"
{{- end }}
