# TODO_IN_THIS_PR(@commoddity): Remove this entire file.
# This is only here to test a second backend for testing the
# service splitting configuration with a simple echo server.
# -- CONTROLLED TRAFFIC SHIFTING --
apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware-http-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: middleware-http
  template:
    metadata:
      labels:
        app: middleware-http
    spec:
      containers:
      - name: http-echo
        image: hashicorp/http-echo:latest
        args: ["-text=Hello from middleware-http", "-listen=:3000"]
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: middleware-http
spec:
  selector:
    app: middleware-http
  ports:
  - port: 3000
    targetPort: 3000
